from django.urls import path
from . import views
from .views import *

# "tempPatientProfile..." are temporary view classes.
# They must be removed once \accounts APIs are written.

urlpatterns = [
    path('tempPatientProfile/', 
         views.ProfileListCreate.as_view(), 
         name ='get_profiles'),
    path('tempPatientProfile/<str:pk>', 
         views.ProfileRetrieveUpdateDestroy.as_view(), 
         name ='create_profile'),
    path('prescription/', 
         views.PrescriptionListCreate.as_view(), 
         name = 'read_create_prescriptions'),
    path('prescription/<str:pk>', 
         views.PrescriptionRetrieveUpdateDestroy.as_view(), 
         name ='update_prescription'),
    path('assessment/', 
         views.AssessmentListCreate.as_view(), 
         name = 'read_create_assessments'),
    path('assessment/<str:pk>', 
         views.AssessmentRetrieveUpdateDestroy.as_view(), 
         name ='update_assessment'),
    path('myPain/', 
         views.MyPainListCreate.as_view(), 
         name = 'read_create_my_pain'),
    path('myPain/<str:pk>', 
         views.MyPainRetrieveUpdateDestroy.as_view(), 
         name ='update_my_pain'),
    path('myMovement/', 
         views.MyMovementListCreate.as_view(), 
         name = 'read_create_my_movement'),
    path('myMovement/<str:pk>', 
         views.MyMovementRetrieveUpdateDestroy.as_view(), 
         name ='update_my_movement'),
    path('myPersonalCare/', 
         views.MyPersonalCareListCreate.as_view(), 
         name = 'read_create_my_personal_care'),
    path('myPersonalCare/<str:pk>', 
         views.MyPersonalCareRetrieveUpdateDestroy.as_view(), 
         name ='update_my_personal_care'),
    path('mySocialHealth/', 
         views.MySocialHealthListCreate.as_view(), 
         name = 'read_create_my_social_health'),
    path('mySocialHealth/<str:pk>', 
         views.MySocialHealthRetrieveUpdateDestroy.as_view(), 
         name ='update_my_social_health'),
    path('myManagement/', 
         views.MyManagementListCreate.as_view(), 
         name = 'read_create_my_management'),
    path('myManagement/<str:pk>', 
         views.MyManagementRetrieveUpdateDestroy.as_view(), 
         name ='update_my_management')
]