# Generated by Django 5.2.17 on 2026-09-23 01:50

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_section', models.CharField(choices=[('onboarding', 'Onboarding'), ('my_pain', 'My Pain'), ('my_movement', 'My Move'), ('my_social_health', 'My Soc Health'), ('my_personal_care', 'My Pers Care'), ('my_management', 'My Manage')], default='my_pain', max_length=30)),
                ('question_key', models.SlugField(max_length=40)),
                ('text', models.CharField(max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'question_option',
                'ordering': ['question_key', 'sort_order'],
                'constraints': [models.UniqueConstraint(fields=('question_key', 'text'), name='unique_option_per_question')],
            },
        ),
        migrations.CreateModel(
            name='QuestionOptionOrdered',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_section', models.CharField(choices=[('onboarding', 'Onboarding'), ('my_pain', 'My Pain'), ('my_movement', 'My Move'), ('my_social_health', 'My Soc Health'), ('my_personal_care', 'My Pers Care'), ('my_management', 'My Manage')], default='my_pain', max_length=30)),
                ('question_key', models.SlugField(max_length=40)),
                ('text', models.CharField(max_length=100)),
                ('question_number', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('option_number', models.PositiveSmallIntegerField(default=0)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'question_option_ordered',
                'ordering': ['question_key', 'option_number'],
                'constraints': [models.UniqueConstraint(fields=('question_key', 'option_number'), name='unique_option_number_per_question')],
            },
        ),
    ]
