# Generated by Django 5.2.17 on 2026-09-17 00:28

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('app_section', models.CharField(choices=[('my_pain', 'My Pain'), ('my_movement', 'My Move'), ('my_social_health', 'My Soc Health'), ('my_personal_care', 'My Pers Care'), ('my_management', 'My Manage')], default='my_pain', max_length=30)),
                ('question_number', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('statement_number', models.PositiveSmallIntegerField(default=0)),
                ('statement_text', models.CharField(max_length=100)),
                ('score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
            ],
            options={
                'db_table': 'assessment_statement',
            },
        ),
        migrations.CreateModel(
            name='PainCharacteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('characteristic', models.CharField(choices=[('Aching', 'Aching'), ('Throbbing', 'Throbbing'), ('Shooting', 'Shooting'), ('Stabbing', 'Stabbing'), ('Gnawing', 'Gnawing'), ('Sharp', 'Sharp'), ('Tender', 'Tender'), ('Burning', 'Burning'), ('Exhausting', 'Exhausting'), ('Tiring', 'Tiring'), ('Penetrating', 'Penetrating'), ('Nagging', 'Nagging'), ('Numb', 'Numb'), ('Miserable', 'Miserable'), ('Unbearable', 'Unbearable')], default='Aching', max_length=50)),
            ],
            options={
                'db_table': 'pain_characteristic',
            },
        ),
        migrations.CreateModel(
            name='PainLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('Head', 'Head'), ('Neck', 'Neck'), ('Shoulder', 'Shoulder'), ('Upper Back', 'Upper Back'), ('Lower Back', 'Lower Back'), ('Leg', 'Leg'), ('Hip', 'Hip'), ('Buttock', 'Buttock'), ('Knee', 'Knee'), ('Other', 'Other')], default='Head', max_length=50)),
            ],
            options={
                'db_table': 'pain_location',
            },
        ),
        migrations.CreateModel(
            name='PainType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('Arthritis', 'Arthritis'), ('Ankylosing spondylitis', 'Ankylosing Spondylitis'), ('Back pain', 'Back Pain'), ("Baker's cyst", 'Bakers Cyst'), ('Bursitis', 'Bursitis'), ('Foot related conditions', 'Foot Related Conditions'), ('Fibromyalgia', 'Fibromyalgia'), ('Gout', 'Gout'), ('Juvenile idiopathic arthritis', 'Juvenile Idiopathic Arthritis'), ('Hand conditions', 'Hand Conditions'), ('Lupus', 'Lupus'), ('Neck pain', 'Neck Pain'), ('Osteoarthritis', 'Osteoarthritis'), ('Osteoporosis', 'Osteoporosis'), ('Paget’s disease', 'Pagets Disease'), ('Perthes’ disease', 'Perthes Disease'), ('Polymyalgia rheumatica', 'Polymyalgia Rheumatica'), ('Psoriatic arthritis', 'Psoriatic Arthritis'), ('Raynaud’s phenomenon', 'Raynauds Phenomenon'), ('Reactive arthritis', 'Reactive Arthritis'), ('Rheumatoid arthritis', 'Rheumatoid Arthritis'), ('Scleroderma', 'Scleroderma'), ('Shoulder pain', 'Shoulder Pain'), ('Sjogren’s disease', 'Sjrogens Disease')], default='Arthritis', max_length=50)),
            ],
            options={
                'db_table': 'pain_type',
            },
        ),
    ]
