# Generated by Django 5.2.17 on 2026-09-23 01:07

import accounts.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=128)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'phone_verification',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'app_user',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('has_diagnosis', models.BooleanField(default=False)),
                ('other_conditions', models.TextField(blank=True)),
                ('assigned_gender_at_birth', models.CharField(blank=True, choices=[('female', 'Female'), ('male', 'Male'), ('intersex', 'Intersex'), ('undisclosed', 'Prefer not to say')], max_length=40)),
                ('birth_year', models.SmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('pain_types', models.ManyToManyField(blank=True, related_name='pain_type_patient_profiles', to='reference.questionoption')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profile',
            },
        ),
        migrations.CreateModel(
            name='SupportLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_phone_number', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked')], default='invited', max_length=10)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='support_links', to='accounts.patientprofile')),
                ('patient_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='patient_user', to=settings.AUTH_USER_MODEL)),
                ('supporter_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='supporting', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_link',
            },
        ),
        migrations.CreateModel(
            name='TermsAndPrivacy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy')], max_length=20)),
                ('document_version', models.CharField(max_length=40)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms_and_privacy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'terms_and_privacy',
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(max_length=128)),
                ('label', models.CharField(blank=True, max_length=80)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trusted_device',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('high_contrast', models.BooleanField(default=False)),
                ('offline_backup', models.BooleanField(default=True)),
                ('microphone_access', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('text_size_percent', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(400)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('phone_number',), name='user_phone_live'),
        ),
        migrations.AddIndex(
            model_name='supportlink',
            index=models.Index(fields=['supporter_user', 'status'], name='support_by_supporter_idx'),
        ),
        migrations.AddIndex(
            model_name='supportlink',
            index=models.Index(fields=['patient_profile'], name='support_by_patient_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportlink',
            constraint=models.CheckConstraint(condition=models.Q(('patient_user', models.F('supporter_user')), _negated=True), name='no_self_support'),
        ),
        migrations.AddConstraint(
            model_name='supportlink',
            constraint=models.UniqueConstraint(fields=('patient_profile', 'supporter_user'), name='one_link_per_pair'),
        ),
        migrations.AddConstraint(
            model_name='supportlink',
            constraint=models.CheckConstraint(condition=models.Q(('supporter_user__isnull', False), models.Q(('invited_phone_number', ''), _negated=True), _connector='OR'), name='supporter_or_phone_required'),
        ),
        migrations.AddConstraint(
            model_name='termsandprivacy',
            constraint=models.UniqueConstraint(fields=('user', 'document_type', 'document_version'), name='one_consent_per_document_version'),
        ),
        migrations.AddConstraint(
            model_name='trusteddevice',
            constraint=models.UniqueConstraint(fields=('user', 'device_id'), name='one_row_per_device'),
        ),
    ]
