# Generated by Django 5.2.17 on 2026-10-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='pain_types',
            field=models.ManyToManyField(blank=True, limit_choices_to={'question_key': 'pain_type'}, related_name='pain_type_patient_profiles', to='reference.questionoption'),
        ),
    ]
