# Generated by Django 5.2.17 on 2026-10-01 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportlink',
            name='can_view_appointments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportlink',
            name='can_view_assessments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supportlink',
            name='can_view_prescriptions',
            field=models.BooleanField(default=False),
        ),
    ]
