# Generated by Django 5.2.17 on 2026-10-08 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patientprofile_pain_types'),
        ('accounts', '0002_supportlink_can_view_appointments_and_more'),
    ]

    operations = [
    ]
