# Generated by Django 5.2.17 on 2026-09-23 01:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_date', models.DateField()),
                ('doctor', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planned')),
                ('health_service', models.CharField(choices=[('General Practitioner', 'General Practitioner'), ('Physiotherapist', 'Physiotherapist'), ('Rheumatologist', 'Rheumatologist'), ('Osteopath', 'Osteopath'), ('Pain Medicine Specialist', 'Pain Medicine Specialist'), ('Orthopaedy Surgeon', 'Orthopaedy Surgeon'), ('Occupational Therapist', 'Occupational Therapist'), ('Other', 'Other')], default='General Practitioner', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_patient', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'appointment',
                'ordering': ['-scheduled_date'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text', models.TextField()),
                ('source', models.CharField(choices=[('suggested', 'Suggested by MPOWERED'), ('patient', 'Written by patient'), ('support', 'Written by support person')], default='patient', max_length=12)),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('is_selected', models.BooleanField(default=True)),
                ('answer_recording', models.URLField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_questions', to='appointment.appointment')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_question',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('text', models.TextField(blank=True)),
                ('recording_file', models.FileField(blank=True, null=True, upload_to='appointment-answers/%Y/%m/')),
                ('transcript', models.TextField(blank=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='question_answer', to='appointment.appointmentquestion')),
            ],
            options={
                'db_table': 'appointment_answer',
            },
        ),
        migrations.CreateModel(
            name='CarePerson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_people', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'care_person',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='care_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_appointments', to='appointment.careperson'),
        ),
        migrations.CreateModel(
            name='AppointmentAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('can_add_questions', models.BooleanField(default=False)),
                ('can_record_answers', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('last_accessed_at', models.DateTimeField(blank=True, null=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='access_grants', to='appointment.appointment')),
                ('last_accessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('support_link', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointment_access', to='accounts.supportlink')),
            ],
            options={
                'db_table': 'appointment_access',
                'indexes': [models.Index(fields=['appointment'], name='access_by_appointment_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='appointmentquestion',
            index=models.Index(fields=['appointment', 'order_index'], name='question_by_appt_idx'),
        ),
        migrations.AddIndex(
            model_name='careperson',
            index=models.Index(fields=['patient_profile'], name='care_person_by_patient_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['scheduled_date'], name='appointment_by_date_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['patient_profile'], name='appointment_by_patient_idx'),
        ),
    ]
