# Generated by Django 5.2.17 on 2026-10-01 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarePerson',
        ),
    ]
