# Generated by Django 5.2.17 on 2026-10-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0002_delete_careperson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_date',
            field=models.DateTimeField(),
        ),
    ]
