# Generated by Django 5.2.17 on 2026-09-23 01:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('appointment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_appointment', to='appointment.appointment')),
                ('support_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_support_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appointment_access_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionAccessLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='appointment.appointmentquestion')),
                ('support_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_support_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_access',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_label', models.CharField(blank=True)),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('export', 'Exported or printed'), ('share', 'Shared'), ('grant', 'Access granted'), ('revoke', 'Access revoked')])),
                ('target_type', models.CharField(choices=[('assessment', 'Assessment'), ('prescription', 'Prescription'), ('appointment', 'Appointment'), ('appointment_question', 'Appointment Question'), ('appointment_answer', 'Appointment Answer'), ('appointment_access', 'Appointment Access'), ('support_link', 'Support Link'), ('generated_document', 'Generated Document'), ('patient_profile', 'Patient Profile')], max_length=40)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('audit_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'audit_entry',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['patient_profile', '-occurred_at'], name='audit_by_patient_idx')],
            },
        ),
    ]
