# Generated by Django 5.2.17 on 2026-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionaccesslog',
            name='question',
        ),
        migrations.RemoveField(
            model_name='questionaccesslog',
            name='support_person',
        ),
        migrations.AlterField(
            model_name='auditentry',
            name='target_type',
            field=models.CharField(choices=[('assessment', 'Assessment'), ('prescription', 'Prescription'), ('appointment', 'Appointment'), ('appointment_question', 'Appointment Question'), ('appointment_answer', 'Appointment Answer'), ('appointment_access', 'Appointment Access'), ('support_link', 'Support Link'), ('patient_profile', 'Patient Profile'), ('pain_chart', 'Pain Chart'), ('pain_profile', 'Pain Profile')], max_length=40),
        ),
        migrations.DeleteModel(
            name='AppointmentAccessLog',
        ),
        migrations.DeleteModel(
            name='QuestionAccessLog',
        ),
    ]
