// replace with active base URL before deployment
const BASE_URL = "http://localhost:8000/api";

/* Instructions:
Call the function for the relevant table in the format api`TableName`(2) with operation values
from {'select', 'create', 'update', 'delete'}, followed by an object of attribute values. Each
function returns the response data (a record or an array of records for 'select' without id),
or null for 'delete'. The exceptions are reference tables (QuestionOption, QuestionOptionOrdered)
which can only be selected, and AuditEntry which can only be selected & created.

- select: pass id to read one record, otherwise the other attributes given are used as filters
          (?attribute_name=value) and an array is returned.
- create: do not add a value for id attribute, it is generated by the server. Attributes set by
          the server (e.g. patient_profile, created_by) must not be given.
- update: only the attributes given are changed (partial update). Attributes that cannot be
          changed are listed, sending a different value for them returns an error.

For tables that have a many-to-many relationship, their attribute value must be entered as an
array of ids, and the attribute in the description will be followed by a [], e.g. locations[].

Use the functions inside a try {...} catch (error) {...}. A failed request throws an ApiError
with the HTTP status (error.status) and the server's error messages (error.data), e.g.
{week_starting: ['An assessment already exists for this week.']}. Deleting a record that other
records depend on returns 409.

Supporters have read-only access to most of a patient's records: their update & delete requests
return 404 and their create requests return 400. Exceptions are listed per table.

For each table the required (NN: not null) & optional object attributes for each operation
are listed. */

export class ApiError extends Error {
    constructor(status, data) {
        super(`API request failed with status ${status}`);
        this.status = status;
        this.data = data;
    }
}

async function request(method, path, body) {
    // FormData bodies (file uploads) set their own multipart Content-Type
    const isFormData = body instanceof FormData;
    const response = await fetch(`${BASE_URL}/${path}`, {
        method: method,
        headers: {
            ...(isFormData ? {} : { 'Content-Type': 'application/json' }),
            Accept: 'application/json',
        },
        body: body === undefined || isFormData ? body : JSON.stringify(body),
    });

    const text = await response.text();
    const data = text ? JSON.parse(text) : null;
    if (!response.ok) {
        throw new ApiError(response.status, data);
    }
    return data;
}

// a file attribute is an object of the device file, e.g. { uri, name, type }
function isFile(value) {
    return value != null && typeof value === 'object' && 'uri' in value;
}

// returns attributes as FormData if any attribute is a file (multipart upload), otherwise as is
function toRequestBody(attributes) {
    if (!Object.values(attributes).some(isFile)) {
        return attributes;
    }
    const formData = new FormData();
    Object.entries(attributes)
        .filter(([, value]) => value != null)
        .forEach(([key, value]) => formData.append(key, value));
    return formData;
}

const ALL_OPERATIONS =['select', 'create', 'update', 'delete'];

/* General function for processing Django APIs, if the table allows the operation*/
async function operate(endpoint, operation, values = {}, allowed = ALL_OPERATIONS) {
    if (!allowed.includes(operation)) {
        throw new Error(`Operation '${operation}' is not allowed for ${endpoint}`);
    }
    const { id, ...attributes } = values;

    if (operation == 'select') {
        if (id) {
            return request('GET', `${endpoint}/${id}`);
        }
        const query = new URLSearchParams();
        Object.entries(attributes)
            .filter(([, value]) => value != null)
            .forEach(([key, value]) => query.append(key, value));
        const queryString = query.toString();
        return request('GET', `${endpoint}/${queryString ? `?${queryString}` : ''}`);

    } else if (operation == 'create') {
        return request('POST', `${endpoint}/`, toRequestBody(attributes));

    } else if (operation == 'update') {
        return request('PATCH', `${endpoint}/${id}`, toRequestBody(attributes));

    } else if (operation == 'delete') {
        return request('DELETE', `${endpoint}/${id}`);
    }

    throw new Error(`Unknown operation: ${operation}`);
}


/* ---------- \accounts ---------- */

/* User:
- select: id, or no filters (only returns own user)
- create: phone_number NN, display_name NN, email
- update: id NN, phone_number, display_name, email
- delete: id NN */
export async function apiUser(operation, values) {
    return operate('user', operation, values);
}

/* PatientProfile:
- select: id, or filter by user (returns own profile & profiles of patients user supports)
- create: has_diagnosis, other_conditions, assigned_gender_at_birth, birth_year, pain_types[]
    - user is set to the user's own, only one profile per user
- update: id NN, has_diagnosis, other_conditions, assigned_gender_at_birth, birth_year,
          pain_types[]
    - user cannot be changed
- delete: id NN */
export async function apiPatientProfile(operation, values) {
    return operate('patientProfile', operation, values);
}

/* UserSettings:
- select: id, or no filters (only returns own settings)
- create: high_contrast, offline_backup, microphone_access, notifications_enabled,
          text_size_percent
    - user is set to the user's own, only one settings record per user
- update: id NN, high_contrast, offline_backup, microphone_access, notifications_enabled,
          text_size_percent
    - user cannot be changed
- delete: id NN */
export async function apiUserSettings(operation, values) {
    return operate('userSettings', operation, values);
}

/* SupportLink:
- select: id, or filter by patient_profile, status (returns links where user is the patient or
          supporter)
- create: supporter_user, invited_phone_number, status
    - one of supporter_user or invited_phone_number is required
    - patient_profile & patient_user are set to the user's own
- update: id NN, status, accepted_at, revoked_at
    - patient_profile, patient_user, supporter_user, invited_phone_number, invited_at cannot be
      changed
    - supporter can only update status (to 'active' or 'revoked')
- delete: id NN
    - patient only */
export async function apiSupportLink(operation, values) {
    return operate('supportLink', operation, values);
}

/* TermsAndPrivacy:
- select: id, or filter by document_type (only returns own records)
- create: document_type NN, document_version NN
    - user is set to the user's own
- update: id NN
    - user, document_type, document_version, accepted_at cannot be changed
- delete: id NN */
export async function apiTermsAndPrivacy(operation, values) {
    return operate('termsAndPrivacy', operation, values);
}


/* ---------- \health ---------- */

/* Prescription:
- select: id, or filter by patient_profile
- create: name NN, dosage NN, frequency NN, strength, started_on, stopped_on, notes,
          strength_unit, form, frequency_unit
    - patient_profile is set to the user's own
- update: id NN, name, dosage, frequency, strength, started_on, stopped_on, notes,
          strength_unit, form, frequency_unit
    - patient_profile cannot be changed
- delete: id NN */
export async function apiPrescription(operation, values) {
    return operate('prescription', operation, values);
}

/* Assessment:
- select: id, or filter by patient_profile, week_starting
- create: week_starting NN, submitted_at, reflection, status
    - patient_profile is set to the user's own, only one assessment per week_starting
- update: id NN, submitted_at, reflection, status
    - patient_profile & week_starting cannot be changed
- delete: id NN */
export async function apiAssessment(operation, values) {
    return operate('assessment', operation, values);
}

/* MyPain:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, current, worst, average, mildest, other_location, other_characteristic,
          completed_at, locations[], characteristics[]
- update: id NN, current, worst, average, mildest, other_location, other_characteristic,
          completed_at, locations[], characteristics[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyPain(operation, values) {
    return operate('myPain', operation, values);
}

/* MyMovement:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, active_hours, walking, sitting, lifting, standing, reflection, score,
          completed_at, general_impacts[]
- update: id NN, active_hours, walking, sitting, lifting, standing, reflection, score,
          completed_at, general_impacts[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyMovement(operation, values) {
    return operate('myMovement', operation, values);
}

/* MyPersonalCare:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, personal_care, sleeping, reflection, score, completed_at,
          general_activities_impact[]
- update: id NN, personal_care, sleeping, reflection, score, completed_at,
          general_activities_impact[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyPersonalCare(operation, values) {
    return operate('myPersonalCare', operation, values);
}

/* MySocialHealth:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, social_life, travelling, mood, relationships, enjoyment_of_life,
          overall_mood, reflection, score, completed_at
- update: id NN, social_life, travelling, mood, relationships, enjoyment_of_life,
          overall_mood, reflection, score, completed_at
    - assessment cannot be changed
- delete: id NN */
export async function apiMySocialHealth(operation, values) {
    return operate('mySocialHealth', operation, values);
}

/* MyManagement:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, otc_medication, exercise, emotion, score, completed_at, medication[]
    - medication must be prescriptions of the assessment's patient
- update: id NN, otc_medication, exercise, emotion, score, completed_at, medication[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyManagement(operation, values) {
    return operate('myManagement', operation, values);
}


/* ---------- \appointment ---------- */

/* Appointment:
- select: id, or filter by patient_profile, status, scheduled_date (returns own appointments &
          appointments user has been given access to)
- create: scheduled_date NN, doctor, status, health_service, notes
    - patient_profile & created_by are set to the user's own
- update: id NN, scheduled_date, doctor, status, health_service, notes
    - patient_profile & created_by cannot be changed
- delete: id NN */
export async function apiAppointment(operation, values) {
    return operate('appointment', operation, values);
}

/* AppointmentQuestion:
- select: id, or filter by appointment NN
- create: appointment NN, text NN, source, order_index, is_selected
    - patient: source can be 'patient' or 'suggested' (default 'patient')
    - supporter: needs can_add_questions access, source is set to 'support'
    - created_by is set to the user
- update: id NN, text, order_index, is_selected
    - appointment, source & created_by cannot be changed
    - patient, or supporter who created the question while they have can_add_questions access
- delete: id NN
    - same as update */
export async function apiAppointmentQuestion(operation, values) {
    return operate('appointmentQuestion', operation, values);
}

/* AppointmentAnswer:
- select: id, or filter by question NN
- create: question NN, text, recording_file, transcript
    - patient, or supporter with can_record_answers access
    - recorded_by is set to the user
    - recording_file is the device audio file as { uri, name, type }, e.g.
      { uri: 'file:///.../answer.m4a', name: 'answer.m4a', type: 'audio/m4a' }
      (audio only, max 20 MB). It is returned as a download URL that needs the user to have
      access to the answer.
- update: id NN, text, recording_file, transcript
    - question cannot be changed
    - recording_file: null removes the recording
    - patient, or supporter with can_record_answers access
- delete: id NN
    - patient only */
export async function apiAppointmentAnswer(operation, values) {
    return operate('appointmentAnswer', operation, values);
}

/* AppointmentAccess:
- select: id, or filter by appointment, support_link (returns access for own appointments &
          access given to user)
- create: appointment NN, support_link NN, can_add_questions, can_record_answers
    - appointment must be the user's own, support_link must be an active link of the same patient
- update: id NN, can_add_questions, can_record_answers, revoked_at
    - appointment, support_link & granted_at cannot be changed
- delete: id NN */
export async function apiAppointmentAccess(operation, values) {
    return operate('appointmentAccess', operation, values);
}


/* ---------- \reference ---------- */

/* QuestionOption:
- select: id, or filter by app_section NN, question_key NN
- create/update/delete: N/A, edit reference data through Django admin */
export async function apiQuestionOption(operation, values) {
    return operate('questionOption', operation, values, ['select']);
}

/* QuestionOptionOrdered:
- select: id, or filter by app_section NN, question_key NN
- create/update/delete: N/A, edit reference data through Django admin */
export async function apiQuestionOptionOrdered(operation, values) {
    return operate('questionOptionOrdered', operation, values, ['select']);
}


/* ---------- \audit ---------- */

/* AuditEntry:
- select: id, or no filters (only returns own audit entries)
- create: action NN, target_type NN, target_id, patient_profile, audit_label, occurred_at,
          context
    - audit_user is set to the user
    - patient_profile must be the user's own or one the user actively supports
- update/delete: N/A, audit entries cannot be changed */
export async function apiAuditEntry(operation, values) {
    return operate('auditEntry', operation, values, ['select', 'create']);
}
