// replace with active base URL before deployment
const BASE_URL = "http://localhost:8000/api";

/* Instructions:
Call the function for the relevant table in the format api`TableName`(2) with operation values
from {'select', 'create', 'update', 'delete'}, followed by an object of attribute values. Each
function returns the response data (a record or an array of records for 'select' without id),
or null for 'delete'.

- select: pass id to read one record, otherwise the other attributes given are used as filters
          (?attribute_name=value) and an array is returned.
- create: do not add a value for id attribute, it is generated by the server. Attributes set by
          the server from the logged in user (e.g. patient_profile) must not be given.
- update: only the attributes given are changed (partial update). Attributes that cannot be
          changed are listed, sending a different value for them returns an error.

For tables that have a many-to-many relationship, their attribute value must be entered as an
array of ids, and the attribute in the description will be followed by a [], e.g. locations[].

Use the functions inside a try {...} catch (error) {...}. A failed request throws an ApiError
with the HTTP status (error.status) and the server's error messages (error.data), e.g.
{week_starting: ['An assessment already exists for this week.']}.

Supporters have read-only access to health tables: their update & delete requests return 404
and their create requests return 400.

For each table the required (NN: not null) & optional object attributes for each operation
are listed. */

export class ApiError extends Error {
    constructor(status, data) {
        super(`API request failed with status ${status}`);
        this.status = status;
        this.data = data;
    }
}

async function request(method, path, body) {
    const response = await fetch(`${BASE_URL}/${path}`, {
        method: method,
        headers: {
            'Content-Type': 'application/json',
            Accept: 'application/json',
        },
        body: body === undefined ? undefined : JSON.stringify(body),
    });

    const text = await response.text();
    const data = text ? JSON.parse(text) : null;
    if (!response.ok) {
        throw new ApiError(response.status, data);
    }
    return data;
}

/* General function for processing Django APIs*/
async function operate(endpoint, operation, values = {}) {
    const { id, ...attributes } = values;

    if (operation == 'select') {
        if (id) {
            return request('GET', `${endpoint}/${id}`);
        }
        const query = new URLSearchParams();
        Object.entries(attributes)
            .filter(([, value]) => value != null)
            .forEach(([key, value]) => query.append(key, value));
        const queryString = query.toString();
        return request('GET', `${endpoint}/${queryString ? `?${queryString}` : ''}`);

    } else if (operation == 'create') {
        return request('POST', `${endpoint}/`, attributes);

    } else if (operation == 'update') {
        return request('PATCH', `${endpoint}/${id}`, attributes);

    } else if (operation == 'delete') {
        return request('DELETE', `${endpoint}/${id}`);
    }

    throw new Error(`Unknown operation: ${operation}`);
}


/* Prescription:
- select: id, or filter by patient_profile
- create: name NN, dosage NN, frequency NN, strength, started_on, stopped_on, notes,
          strength_unit, form, frequency_unit
    - patient_profile is set to the user's own
- update: id NN, name, dosage, frequency, strength, started_on, stopped_on, notes,
          strength_unit, form, frequency_unit
    - patient_profile cannot be changed
- delete: id NN */
export async function apiPrescription(operation, values) {
    return operate('prescription', operation, values);
}

/* Assessment:
- select: id, or filter by patient_profile, week_starting
- create: week_starting NN, submitted_at, reflection, status
    - patient_profile is set to the user's own, only one assessment per week_starting
- update: id NN, submitted_at, reflection, status
    - patient_profile & week_starting cannot be changed
- delete: id NN */
export async function apiAssessment(operation, values) {
    return operate('assessment', operation, values);
}

/* MyPain:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, current, worst, average, mildest, other_location, other_characteristic,
          completed_at, locations[], characteristics[]
- update: id NN, current, worst, average, mildest, other_location, other_characteristic,
          completed_at, locations[], characteristics[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyPain(operation, values) {
    return operate('myPain', operation, values);
}

/* MyMovement:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, active_hours, walking, sitting, lifting, standing, reflection, score,
          completed_at, general_impacts[]
- update: id NN, active_hours, walking, sitting, lifting, standing, reflection, score,
          completed_at, general_impacts[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyMovement(operation, values) {
    return operate('myMovement', operation, values);
}

/* MyPersonalCare:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, personal_care, sleeping, reflection, score, completed_at,
          general_activities_impact[]
- update: id NN, personal_care, sleeping, reflection, score, completed_at,
          general_activities_impact[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyPersonalCare(operation, values) {
    return operate('myPersonalCare', operation, values);
}

/* MySocialHealth:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, social_life, travelling, mood, relationships, enjoyment_of_life,
          overall_mood, reflection, score, completed_at
- update: id NN, social_life, travelling, mood, relationships, enjoyment_of_life,
          overall_mood, reflection, score, completed_at
    - assessment cannot be changed
- delete: id NN */
export async function apiMySocialHealth(operation, values) {
    return operate('mySocialHealth', operation, values);
}

/* MyManagement:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, otc_medication, exercise, emotion, score, completed_at, medication[]
    - medication must be prescriptions of the assessment's patient
- update: id NN, otc_medication, exercise, emotion, score, completed_at, medication[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyManagement(operation, values) {
    return operate('myManagement', operation, values);
}
