// replace with active base URL before deployment
const BASE_URL = "http://localhost:8000/api";

/* Instructions:
Call the function for the relevant table in the format api`TableName`(2) with operation values
from {'select', 'create', 'update', 'delete'}, followed by an object of attribute values. Each
function returns the response data (a record or an array of records for 'select' without id),
or null for 'delete'. The exceptions are reference tables (QuestionOption, QuestionOptionOrdered)
which can only be selected, and AuditEntry which can only be selected & created.

- select: pass id to read one record, otherwise the other attributes given are used as filters
          (?attribute_name=value) and an array is returned.
- create: do not add a value for id attribute, it is generated by the server. Attributes set by
          the server (e.g. patient_profile, created_by) must not be given.
- update: only the attributes given are changed (partial update). Attributes that cannot be
          changed are listed, sending a different value for them returns an error.

example call: 
const myMovement = await apiMyMovement('create', {
    'assessment': assessment_uuid,
    'active_hours': 12,
    'walking': walking_uuid, // QuestionOptionOrdered id
    'sitting': sitting_uuid, // QuestionOptionOrdered id
    'lifting': lifting_uuid, // QuestionOptionOrdered id
    'standing': standing_uuid, // QuestionOptionOrdered id
    'general_impacts': ['general_impact_1_uuid', // QuestionOptionOrdered ids
                        'general_impact_2_uuid], 
    'reflection': 'Walking was easier this week.',
    'score': 9,
    'completed_at': new Date().toISOString(),
})
        
For tables that have a many-to-many relationship, their attribute value must be entered as an
array of ids, and the attribute in the description will be followed by a [], e.g. locations[].

Use the functions inside a try/catch block. A failed request throws an ApiError
with the HTTP status (error.status) and the server's error messages (error.data), e.g.
{week_starting: ['An assessment already exists for this week.']}. Deleting a record that other
records depend on returns 409.

Supporters have read-only access to most of a patient's records: their update & delete requests
return 404 and their create requests return 400. Exceptions are listed per table.

For each table the required (NN: not null) & optional object attributes for each operation
are listed. */

export class ApiError extends Error {
    constructor(status, data) {
        super(`API request failed with status ${status}`);
        this.status = status;
        this.data = data;
    }
}

async function request(method, path, body) {
    // FormData bodies (file uploads) set their own multipart Content-Type
    const isFormData = body instanceof FormData;
    const response = await fetch(`${BASE_URL}/${path}`, {
        method: method,
        headers: {
            ...(isFormData ? {} : { 'Content-Type': 'application/json' }),
            Accept: 'application/json',
        },
        // undefined if the operation is delete
        body: body === undefined || isFormData ? body : JSON.stringify(body),
    });

    // parse response
    const text = await response.text();
    const data = text ? JSON.parse(text) : null;
    if (!response.ok) {
        throw new ApiError(response.status, data);
    }
    return data;
}

// a file attribute is an object of the device file, e.g. { uri, name, type }
function isFile(value) {
    return value != null && typeof value === 'object' && 'uri' in value;
}

// returns attributes as FormData if any attribute is a file (multipart upload), otherwise as is
function toRequestBody(attributes) {
    if (!Object.values(attributes).some(isFile)) {
        return attributes;
    }
    const formData = new FormData();
    Object.entries(attributes)
        .filter(([, value]) => value != null)
        .forEach(([key, value]) => formData.append(key, value));
    return formData;
}

// helper function for processing Django APIs, if the table allows the operation
async function operate(endpoint, operation, values = {}) {
    if (!['select', 'create', 'update', 'delete'].includes(operation)) {
        throw new Error(`Operation '${operation}' is not allowed for ${endpoint}`);
    }

    // split id from body attributes
    const { id, ...attributes } = values;

    if (operation == 'select') {

        // if id is given, return specific selection
        if (id) {
            return request('GET', `${endpoint}/${id}`);
        }

        // if no id given, search by given filter parameters
        const query = new URLSearchParams();
        // convert list of attributes into an array of key value pairs
        Object.entries(attributes)
            .filter(([, value]) => value != null)
            .forEach(([key, value]) => query.append(key, value));
        // queryString is a string of key=value pairs separated by "&"
        const queryString = query.toString();
        // if there are search parameters, add "?"
        return request('GET', `${endpoint}/${queryString ? `?${queryString}` : ''}`);

    } else if (operation == 'create') {
        return request('POST', `${endpoint}/`, toRequestBody(attributes));

    } else if (operation == 'update') {
        return request('PATCH', `${endpoint}/${id}`, toRequestBody(attributes));

    } else if (operation == 'delete') {
        return request('DELETE', `${endpoint}/${id}`);
    }

    throw new Error(`Unknown operation: ${operation}`);
}

/* User:
- select: id, or no filters (only returns own user)
- create: phone_number NN, display_name NN, email
    - phone_number must be local Australian number with no spaces
- update: id NN, phone_number, display_name, email
    - phone_number must be local Australian number with no spaces
- delete: id NN */
export async function apiUser(operation, values) {
    return operate('user', operation, values);
}

/* PatientProfile:
- select: id, or filter by user (returns own profile & profiles of patients user supports)
- create: has_diagnosis, other_conditions, assigned_gender_at_birth, birth_year, pain_types[]
    - user is set to the user's own, only one profile per user
- update: id NN, has_diagnosis, other_conditions, assigned_gender_at_birth, birth_year,
          pain_types[]
    - id cannot be changed
- delete: id NN */
export async function apiPatientProfile(operation, values) {
    return operate('patientProfile', operation, values);
}

/* UserSettings:
- select: id, or no filters (only returns own settings)
- create: high_contrast, offline_backup, microphone_access, notifications_enabled,
          text_size_percent
    - user is set to the user's own, only one settings record per user
- update: id NN, high_contrast, offline_backup, microphone_access, notifications_enabled,
          text_size_percent
    - user cannot be changed
- delete: id NN */
export async function apiUserSettings(operation, values) {
    return operate('userSettings', operation, values);
}

/* SupportLink:
- select: id, or filter by patient_profile, status (returns links where user is the patient or
          supporter)
- create: supporter_user, invited_phone_number
    - one of supporter_user or invited_phone_number is required, patient_profile 
      & patient_user are set to the user's own, status is set to INVITED
- update: id NN, status, accepted_at, revoked_at
    - patient user cannot update their own SupportLinks
    - supporter user can only update status (to 'active' or 'revoked')
- delete: id NN
    - only patient can delete */
export async function apiSupportLink(operation, values) {
    return operate('supportLink', operation, values);
}

/* TermsAndPrivacy:
- select: id, or filter by document_type (only returns own records)
- create: document_type NN, document_version NN
    - user is set to the user's own
- update: N/A
- delete: N/A NN */
export async function apiTermsAndPrivacy(operation, values) {
    return operate('termsAndPrivacy', operation, values,  ['select', 'create']);
}

/* PhoneVerification:
- create: phone_number NN
    - phone_number must be local Australian number with no spaces
    - code, attempts, used_at, expires_at are auto generated
- select/update/delete: N/A */
export async function apiPhoneVerification(operation, values) {
    return operate('phoneVerification', operation, values, ['create']);
}

/* TrustedDevice:
- select: id, or no filters (only returns own devices)
- create: device_id NN, label
    - user is set to the user's own, last_seen_at is auto updated
- update: id NN, label, revoked_at
    - user & device_id cannot be changed
- delete: id NN */
export async function apiTrustedDevice(operation, values) {
    return operate('trustedDevice', operation, values);
}

/* Prescription:
- select: id, or filter by patient_profile
- create: name NN, dosage NN, frequency NN, strength, started_on, stopped_on, notes,
          strength_unit, form, frequency_unit
    - patient_profile is set to the user's own
- update: id NN, name, dosage, frequency, strength, started_on, stopped_on, notes,
          strength_unit, form, frequency_unit
    - patient_profile cannot be changed
- delete: id NN */
export async function apiPrescription(operation, values) {
    return operate('prescription', operation, values);
}

/* Assessment:
- select: id, or filter by patient_profile, week_starting
- create: week_starting NN, submitted_at, reflection, status
    - patient_profile is set to the user's own, one assessment per week_starting,
      week_starting must be on a Monday
- update: id NN, submitted_at, reflection, status
    - patient_profile & week_starting cannot be changed
- delete: id NN */
export async function apiAssessment(operation, values) {
    return operate('assessment', operation, values);
}

/* MyPain:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, current, worst, average, mildest, other_location, other_characteristic,
          completed_at, locations[], characteristics[]
- update: id NN, current, worst, average, mildest, other_location, other_characteristic,
          completed_at, locations[], characteristics[]
    - assessment cannot be changed
- delete: id NN */
export async function apiMyPain(operation, values) {
    return operate('myPain', operation, values);
}

/* MyMovement:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, active_hours, walking, sitting, lifting, standing, reflection,
          completed_at, general_impacts[]
    - score is auto generated
- update: id NN, active_hours, walking, sitting, lifting, standing, reflection,
          completed_at, general_impacts[]
    - assessment cannot be changed, score is auto generated
- delete: id NN */
export async function apiMyMovement(operation, values) {
    return operate('myMovement', operation, values);
}

/* MyPersonalCare:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, personal_care, sleeping, reflection, completed_at,
          general_activities_impact[]
    - score is auto generated
- update: id NN, personal_care, sleeping, reflection, completed_at,
          general_activities_impact[]
    - assessment cannot be changed, , score is auto generated
- delete: id NN */
export async function apiMyPersonalCare(operation, values) {
    return operate('myPersonalCare', operation, values);
}

/* MySocialHealth:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, social_life, travelling, mood, relationships, enjoyment_of_life,
          overall_mood, reflection, completed_at
    - score is auto generated
- update: id NN, social_life, travelling, mood, relationships, enjoyment_of_life,
          overall_mood, reflection, completed_at
    - assessment cannot be changed, score is auto generated
- delete: id NN */
export async function apiMySocialHealth(operation, values) {
    return operate('mySocialHealth', operation, values);
}

/* MyManagement:
- select: id, or filter by assessment NN, patient_profile
- create: assessment NN, otc_medication, exercise, emotion, completed_at, medication[]
    - medication must be prescriptions of the assessment's patient, score is 
      auto generated
- update: id NN, otc_medication, exercise, emotion, completed_at, medication[]
    - assessment cannot be changed, medication must be prescriptions of the
      assessment's patient, score is auto generated
- delete: id NN */
export async function apiMyManagement(operation, values) {
    return operate('myManagement', operation, values);
}

/* Appointment:
- select: id, or filter by patient_profile, status, scheduled_date (returns own appointments &
          appointments user has been given access to)
- create: scheduled_date NN, doctor, status, health_service, notes
    - patient_profile is set to user's own or their patients, created_by is set to 
      the user's own, scheduled_date must be in the present or future
    - user must have a patient_profile
- update: id NN, scheduled_date, doctor, status, health_service, notes
    - patient_profile & created_by cannot be changed
    - user can only update their own appointments where they are a patient
- delete: id NN */
export async function apiAppointment(operation, values) {
    return operate('appointment', operation, values);
}

/* AppointmentQuestion:
- select: id, or filter by appointment NN
    - can only see one's own appointment questions or patient's appointment questions
- create: appointment NN, text NN, source, is_selected
    - created_by is set to the user, order_index is auto generated
    - patient, or supporter with can_add_questions=true in AppointmentAccess can create
    - if user is patient: source can be PATIENT (default) or SUGGESTED
    - if user is supporter: source can be SUPPORT (default) or SUGGESTED
- update: id NN, text, order_index, is_selected
    - appointment, source, created_by cannot be changed
    - if user is supporter: source can be SUPPORT (default) or SUGGESTED, can only create if 
      can_add_questions=True in AppointmentAccess
- delete: id NN
    - same as update */
export async function apiAppointmentQuestion(operation, values) {
    return operate('appointmentQuestion', operation, values);
}

/* AppointmentAnswer:
- select: id, or filter by question NN 
    - can only see one's own appointment's answers or patient's appointment's answers
- create: question NN, text, recording_file, transcript
    - patient, or supporter with can_record_answers=true in AppointmentAccess can create
    - recorded_by is set to the user
    - recording_file is the device audio file as { uri, name, type }, e.g.
      { uri: 'file:///.../answer.m4a', name: 'answer.m4a', type: 'audio/m4a' }
      (audio only, max 20 MB). It is returned as a download URL that needs the user to have
      access to the answer.
- update: id NN, text, recording_file, transcript
    - question cannot be changed
    - recording_file: null removes the recording    
    - patient, or supporter with can_record_answers=true in AppointmentAccess can create
- delete: id NN
    - patient only */
export async function apiAppointmentAnswer(operation, values) {
    return operate('appointmentAnswer', operation, values);
}

/* AppointmentAccess:
- select: id, or filter by appointment, support_link (returns access for own appointments &
          access given to user)
- create: appointment NN, support_link NN, can_add_questions NN, can_record_answers NN
    - appointment must be the user's own, support_link must be an active link of the same patient
    - granted_at is auto generated
- update: id NN, can_add_questions, can_record_answers, revoked_at
    - appointment, support_link & granted_at cannot be changed
- delete: id NN */
export async function apiAppointmentAccess(operation, values) {
    return operate('appointmentAccess', operation, values);
}

/* QuestionOption:
- select: id, or filter by app_section NN, question_key NN
- create/update/delete: N/A, edit reference data through Django admin */
export async function apiQuestionOption(operation, values) {
    return operate('questionOption', operation, values, ['select']);
}

/* QuestionOptionOrdered:
- select: id, or filter by app_section NN, question_key NN
- create/update/delete: N/A, edit reference data through Django admin */
export async function apiQuestionOptionOrdered(operation, values) {
    return operate('questionOptionOrdered', operation, values, ['select']);
}

/* AuditEntry:
- select: id, or no filters (only returns own audit entries)
- create: action NN, target_type NN, target_id, patient_profile, audit_label, occurred_at,
          context
    - audit_user is set to the user
    - patient_profile must be the user's own
- update/delete: N/A */
export async function apiAuditEntry(operation, values) {
    return operate('auditEntry', operation, values, ['select', 'create']);
}
