# Generated by Django 5.2.17 on 2026-09-23 01:50

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('reference', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reflection', models.CharField(blank=True, max_length=300, null=True)),
                ('week_starting', models.DateField()),
                ('status', models.CharField()),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assessments', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'assessment',
                'ordering': ['-week_starting'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(choices=[('pain_chart', 'Pain Chart'), ('pain_profile', 'Pain Profile'), ('appointment', 'Appointment Summary')], max_length=20)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_until', models.DateField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'generated_document',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='MyMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_hours', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(168)])),
                ('reflection', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(26)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_movement', to='health.assessment')),
                ('general_impacts', models.ManyToManyField(blank=True, limit_choices_to={'question_key': 'movement_general_impacts'}, related_name='+', to='reference.questionoptionordered')),
                ('lifting', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'movement_lifting'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('sitting', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'movement_sitting'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('standing', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'movement_standing'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('walking', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'movement_walking'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
            ],
            options={
                'db_table': 'my_movement',
            },
        ),
        migrations.CreateModel(
            name='MyPain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('worst', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('average', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('mildest', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('other_location', models.CharField(blank=True, max_length=100, null=True)),
                ('other_characteristic', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_pain', to='health.assessment')),
                ('characteristics', models.ManyToManyField(blank=True, limit_choices_to={'question_key': 'pain_characteristic'}, related_name='+', to='reference.questionoption')),
                ('locations', models.ManyToManyField(blank=True, limit_choices_to={'question_key': 'pain_location'}, related_name='+', to='reference.questionoption')),
            ],
            options={
                'db_table': 'my_pain',
            },
        ),
        migrations.CreateModel(
            name='MyPersonalCare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reflection', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_personal_care', to='health.assessment')),
                ('general_activities_impact', models.ManyToManyField(blank=True, limit_choices_to={'question_key': 'care_general_impacts'}, related_name='+', to='reference.questionoptionordered')),
                ('personal_care', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'care_personal_care'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('sleeping', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'care_sleeping'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
            ],
            options={
                'db_table': 'my_personal_care',
            },
        ),
        migrations.CreateModel(
            name='MySocialHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mood', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('relationships', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('enjoyment_of_life', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('reflection', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(40)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_social_health', to='health.assessment')),
                ('overall_mood', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'social_overall_mood'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('social_life', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'social_social_life'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('travelling', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'social_travelling'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
            ],
            options={
                'db_table': 'my_social_health',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('dosage', models.PositiveSmallIntegerField()),
                ('strength', models.PositiveIntegerField(default=0)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('stopped_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('strength_unit', models.CharField(choices=[('mg', 'mg'), ('g', 'g'), ('%', '%'), ('μg', 'μg'), ('iu', 'IU')], default='mg', max_length=10)),
                ('form', models.CharField(choices=[('tablets', 'Tablets'), ('capsules', 'Capsules'), ('liquid', 'Liquid'), ('drops', 'Drops'), ('injections', 'Injections'), ('spray', 'Spray'), ('mL', 'mL'), ('patches', 'Patches')], default='tablets', max_length=20)),
                ('frequency', models.PositiveSmallIntegerField()),
                ('frequency_unit', models.CharField(choices=[('hour(s)', 'Hour(s)'), ('day(s)', 'Day(s)'), ('week(s)', 'Week(s)'), ('month(s)', 'Month(s)')], default='hour(s)', max_length=10)),
                ('patient_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perscriptions', to='accounts.patientprofile')),
            ],
            options={
                'db_table': 'prescription',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MyManagement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otc_medication', models.CharField(blank=True, max_length=300, null=True)),
                ('emotion', models.CharField(blank=True, max_length=300, null=True)),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='my_management', to='health.assessment')),
                ('exercise', models.ForeignKey(blank=True, limit_choices_to={'question_key': 'management_exercise'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='reference.questionoptionordered')),
                ('medication', models.ManyToManyField(blank=True, related_name='my_management_prescriptions', to='health.prescription')),
            ],
            options={
                'db_table': 'my_management',
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['patient_profile', 'week_starting'], name='assessment_by_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('patient_profile', 'week_starting'), name='one_assessment_per_week'),
        ),
        migrations.AddIndex(
            model_name='generateddocument',
            index=models.Index(fields=['patient_profile', '-generated_at'], name='document_by_patient_idx'),
        ),
    ]
