# Generated by Django 5.2.17 on 2026-09-26 06:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempPatientProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='assessment',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assessments', to='health.temppatientprofile'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='health.temppatientprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perscriptions', to='health.temppatientprofile'),
        ),
    ]
