# Generated by Django 5.2.17 on 2026-09-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_temppatientprofile_alter_assessment_patient_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('expired', 'Expired')], default='draft', max_length=10),
        ),
        migrations.DeleteModel(
            name='GeneratedDocument',
        ),
    ]
