# Generated by Django 5.2.17 on 2026-09-30 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('health', '0003_alter_assessment_status_delete_generateddocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assessments', to='accounts.patientprofile'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='patient_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='accounts.patientprofile'),
        ),
        migrations.RenameField(
            model_name='mymovement',
            old_name='assessment_id',
            new_name='assessment',
        ),
        migrations.RenameField(
            model_name='mypain',
            old_name='assessment_id',
            new_name='assessment',
        ),
        migrations.DeleteModel(
            name='TempPatientProfile',
        ),
    ]
